---
- hosts: all
  sudo: yes
  tasks:
  - name: install dev packages
    yum: name="@Development tools" state=present

  - name: install wget
    yum: name=wget state=present

  - name: install git
    yum: name=git state=present

  - name: upgrade all packages
    yum: name=* state=latest

