---
- hosts: base
  sudo: yes
  tasks:

  - name: get the latest gluster repo
    command: wget -P /etc/yum.repos.d http://download.gluster.org/pub/gluster/glusterfs/LATEST/RHEL/glusterfs-epel.repo creates=/etc/yum.repos.d/glusterfs-epel.repo

  - name: ensure the epel-release package is installed
    yum: name=epel-release state=present

  - name: install userspace-rcu development package
    yum: name=userspace-rcu-devel state=present

  - name: install gluster server package
    yum: name=glusterfs-server state=present

  - name: install firewalld package
    yum: name=firewalld state=present

  - name: ensure firewalld is enabled
    service: name=firewalld enabled=yes state=restarted

  - name: configure glusterd service firewall rules
    firewalld: port=24007-24009/tcp permanent=true immediate=true state=enabled

  - name: configure glusterd brick firewall rules
    firewalld: port=49152-49154/tcp permanent=true immediate=true state=enabled

  - name: start the gluster server services
    service: name=glusterd enabled=yes state=restarted

  - name: install glusterfs
    yum: name=glusterfs state=present

  - name: install gluster fuse
    yum: name=glusterfs-fuse state=present

  - name: create gluster volume 'gluster'
    gluster_volume: brick='/mnt/gluster' cluster='{{ local_name }},{{ remote_name }}' force=true name=gluster replicas=2 state=present transport=tcp
    run_once: true

  - name: make gluster shared directory /mnt/shared
    file: path=/mnt/shared owner=root group=root mode=0755 state=directory

  - name: mount gluster storage on gluster-pool
    mount: name=/mnt/shared src="{{ local_name }}:/gluster" opts=defaults,_netdev fstype=glusterfs state=mounted
