# KVM passthrough configuration
# Libvirt Setup
- hosts: all
  sudo: yes
  vars:
    nested: y
    mgmt_int: bond0
    mgmt_br: br0
    network:  "bridge:{{mgmt_br}}"
    cdrom: "/mnt/shared/centos-7-min.iso"
    disk: "/mnt/shared/libvirt/ctrl-a.qcow2,size=20,format=qcow2"
    extra_args: "ks=file:/kick-min.ks console=tty0 console=ttyS0,115200"
    cloud_path: /mnt/shared/libvirt/
    cloud_image_src: http://mirror.ash.fastserv.com/pub/linux/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1503-01.iso
    vms:
      ctrl-a:
        mem_kb: '4194304'
        num_vcpu: '4'
        last_octet: '11'
      ctrl-b:
        mem_kb: '4194304'
        num_vcpu: '4'
        last_octet: '12'
      mysql-a:
        mem_kb: '2097152'
        num_vcpu: '2'
        last_octet: '13'
      mysql-b:
        mem_kb: '2097152'
        num_vcpu: '2'
        last_octet: '14'

  tasks:

  - name: ensure libvirt is installed
    yum: name=@virt*  state=present

  - name: ensure libguestfs-tools are available
    yum: name=libguestfs-tools state=present

  - name: ensure semanage tools are available
    yum: name=policycoreutils-python state=present

  - name: ensure KVM can run in 'nested' state
    template:
      src: ./roles/templates/kvm.conf.j2
      dest: /etc/modprobe.d/kvm.conf

  - name: remove the kvm module
    command: rmmod kvm-intel

  - name: insert the kvm module
    command: modprobe kvm-intel

  - name: enable libvirtd service
    service: name=libvirtd state=restarted enabled=yes

#
# Map the "mgmt_int" interface to br0
#

  - name: duplicate the mgmt_int interface info to the br0 bridge
    command: cp /etc/sysconfig/network-scripts/ifcfg-{{mgmt_int}} /etc/sysconfig/network-scripts/ifcfg-br0 creates=/etc/sysconfig/newtork-scritps/ifcfg-br0

  - name: update config of br0 for bridging
    command: sed -i -e'/HWADDR/d' -e'/UUID/d' -e's/{{mgmt_int}}/br0/' -e's/Ethernet/Bridge/' /etc/sysconfig/network-scripts/ifcfg-br0

  - name: add "DELAY=0" param to bridge
    lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-br0 state=present line='DELAY=0'

  - name: change BOOTPROTO=none in mgmt_int
    lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-{{mgmt_int}} state=present regexp='BOOTPROTO*' line='BOOTPROTO=none'

  - name: add mgmt_int to br0 bridge
    lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-{{mgmt_int}} state=present line='BRIDGE=br0'

  - name: restart the network service
    service: name=network state=restarted

  - name: ensure forwarding in sysctl
    lineinfile: dest=/etc/sysctl.conf line='net.ipv4.ip_forward=1' state=present
    notify: sysctl_restart

  - name: copy xml network definintion
    template: src=./roles/templates/network.xml.j2 dest=/tmp/{{mgmt_br}}.xml

  - name: stop management bridge
    command: virsh net-destroy default
    ignore_errors: yes

  - name: cancel the autostart of management
    command: virsh net-autostart default --disable
    ignore_errors: yes

  - name: add network to libvirt
    command: virsh net-define /tmp/{{mgmt_br}}.xml creates=/etc/libvirt/qemu/networks/br0.xml

  - name: ensure auto-start for mgmt_br
    command: virsh net-autostart {{mgmt_br}} 
    ignore_errors: yes

#
# Set up Libvirt storage on the shared gluster disk
#

  - name: create a libvirt directory on the shared filesystem
    file: path=/mnt/shared/libvirt owner=root group=root mode=0755 state=directory

  - name: update selinux for virtualization
    command: semanage fcontext -a -t virt_image_t "/mnt/shared/libvirt(/.*)?"

  - name: restore the selinux service for the new directory
    command: restorecon -R /mnt/shared/libvirt

#
# Add VMs via libvirt for control and database
#

  - name: upload vm xml
    template: src=./roles/templates/vm.xml.j2 dest=/mnt/shared/{{item.key}}.xml
    #debug: msg="{{ item.key }} and {{item.value.mem_kb}}"
    with_dict: "{{ vms }}"
    run_once: true

  - name: upload kickstart file
    template: src=./roles/templates/kick-min.ks.j2 dest=/mnt/shared/kick-min.ks
    run_once: true

  - name: upload minimal ISO for creating cloud_image
    get_url: url="{{cloud_image_src}}" dest=/mnt/shared/centos-7-min.iso
    run_once: true

  # - name: duplicate qcow for vms
  #   command: /bin/cp /mnt/shared/libvirt/centos-7-0615.qcow2 /mnt/shared/libvirt/{{item.key}}.qcow2 creates=/mnt/shared/libvirt/{{item.key}}.qcow2
  #   with_dict: "{{ vms }}"
  #   run_once: true

  - name: create default pool
    command: virsh pool-define-as --name default --type dir --target /mnt/shared/libvirt
    ignore_errors: yes

  - name: autostart default pool
    command: virsh pool-start default
    ignore_errors: yes

  - name: build pool
    command: virsh pool-build default
    ignore_errors: yes

  - name: start pool
    command: virsh pool-autostart default
    ignore_errors: yes

  - name: update selinux for virtualization
    command: semanage fcontext -a -t virt_image_t "/mnt/shared/libvirt(/.*)?"

  - name: restore the selinux service for the new directory
    command: restorecon -R /mnt/shared/libvirt

  - name: build a VM for control and for compute
    command: virt-install --hvm --name {{item.key}} --initrd-inject=/mnt/shared/kick-min.ks --ram ((item.value.ram/1024}} --vcpu {{item.value.num_vcpu}} --extra-args={{extra_args}} --cdrom={{cdrom}} --disk {{disk}} --network {{network}} --nographics
    with_dict: "{{ vms }}"
   
  handlers:

  - name: sysctl_restart
    command: sysctl -p